collections_config:
  pages:
    path: ''
    icon: wysiwyg

  posts:
    path: data/blog
    icon: library_books
    parser: json
    output: true
    url: "/blog/[slug]/"
    _inputs:
      title:
        label: "Titre de l'article"
        type: text
      slug:
        label: "Slug (URL)"
        type: text
      date:
        label: "Date de publication"
        type: datetime
      image:
        label: "Image de couverture"
        type: image
      excerpt:
        label: "Résumé (160 caractères max)"
        type: textarea
      body:
        label: "Contenu de l'article"
        type: markdown
      seo_title:
        label: "SEO Title"
        type: text
      meta_description:
        label: "Meta Description"
        type: textarea

data_config:
  site:
    path: data/content.json
  blog_index:
    path: data/blog-index.json
    source: data/blog

timezone: Etc/UTC
output: .
