baseURL = "https://gsfconsultinginternational.com/"
languageCode = "fr-fr"
title = "GSF Consulting International"
publishDir = "public"

[params]
  description = "Expertise Juridique & IA"
  author = "Gilles Feliho"
